version: "3"
services:
  user-service:
    image: user-service
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user-service
    ports:
      - "3000:80"
    environment:
      - PORT=80
      - RABBITMQ_SERVER=amqp://guest:guest@rabbitmq:5672
    depends_on:
      - rabbitmq
    restart: "no"

  wallet-service:
    image: wallet-service
    build:
      context: ./wallet-service
      dockerfile: Dockerfile
    container_name: wallet-service
    ports:
      - "3001:80"
    environment:
      - PORT=80
    restart: "no"

  notification-service:
    image: notification-service
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    container_name: notification-service
    ports:
      - "3002:80"
    environment:
      - PORT=80
      - RABBITMQ_SERVER=amqp://guest:guest@rabbitmq:5672
    depends_on:
      - rabbitmq
    restart: "no"

  rabbitmq:
    image: rabbitmq:3.8.1-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - "5672"
      - "15672"
    restart: "always"
